#Application Configuration
server:
  port: 8092

# To See H2 Console in Browser:
# http://localhost:8092/h2-console
# Enabling H2 Console
spring:
# ===============================
# boot / admin
# ===============================
  boot:
    admin:
        client:  
            url: http://admin-service:8086 
  h2:
    console:
      enabled: true
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:h2:mem:customerDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
# ===============================
# EUREKA
# ===============================
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service-primary:8083/eureka/,http://egistry-service-secondary:8084/eureka/,http://registry-service-tertiary:8085/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"