server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service-primary:8083/eureka/,http://registry-service-secondary:8084/eureka/,http://registry-service-tertiary:8085/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: shopping-service
          uri: lb://shopping-service
          predicates:
            - Path=/invoices/**
        - id: security-service
          uri: lb://security-service
          predicates:
              - Path=/security/**
          filters:
              - RewritePath=/(?<path>.*), /$\{path}
